name: Deploy to HubSpot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v2.0.1
        with:
          src_dir: faq.module
          dest_dir: '11_Bytes child/modules/static modules/FAQ lean.module'
          account_id: ${{ secrets.HUBSPOT_PORTAL_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_TOKEN }}