name: Deploy to HubSpot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Module to HubSpot
        env:
          HUBSPOT_ACCOUNT_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_TOKEN }}
        run: |
          npx --yes --package=@hubspot/cli@^7 --call='hs cms upload "faq.module" "11_Bytes child/modules/static modules/FAQ lean.module" --use-env'