name: Deploy to HubSpot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Ermöglicht den manuellen Start über die GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Generate HubSpot Config
        env:
          HUBSPOT_PERSONAL_ACCESS_TOKEN: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_TOKEN }}
          PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
        run: |
          cat << EOF > hubspot.config.yml
          defaultPortal: 'PROD'
          portals:
            - name: 'PROD'
              portalId: $PORTAL_ID
              personalAccessKey: '$HUBSPOT_PERSONAL_ACCESS_TOKEN'
          EOF

      - name: Deploy Module to HubSpot
        run: |
          hs upload "faq.module" "11_Bytes child/modules/static modules/FAQ lean.module"